#pragma once

#define FLEX_BUTTON_LEFT SDL_BUTTON_LEFT
#define FLEX_BUTTON_MIDDLE SDL_BUTTON_MIDDLE
#define FLEX_BUTTON_RIGHT SDL_BUTTON_RIGHT
#define FLEX_BUTTON_X1 SDL_BUTTON_X1
#define FLEX_BUTTON_X2 SDL_BUTTON_X2
